---
- hosts: all
  sudo: True
  roles:
    - ansible-jenkins-swarm
     
  vars:     
    docker_files_generated_directory: ""  
    jenkins_home: /var/lib/jenkins
    jenkins_username: tbd
    jenkins_password: tbd
