---
- hosts: all
  become: true

  roles:
    - { role: ./,
        docker_files_enable: yes,
        jenkins_home: /var/lib/jenkins,
        jenkins_username: tbd,
        jenkins_password: tbd,
        user: root,
        home: /root,
        subversion_owner_home: "/root/.subversion",
        subversion_previous_enabled: true,
        subversion_previous_codename: precise,
        subversion_rabbitvcs_enabled: no,
        subversion_diff_enabled: no,
        subversion_major    : '1',
        subversion_minor    : '6',
        subversion_revision : '17',
        subversion_version : "{{subversion_major}}.{{subversion_minor}}.{{subversion_revision}}",
        subversion_ubuntu: '{{ subversion_version }}dfsg-3ubuntu3',
      }

#- include: docker/integration-tests.yml
