---
- hosts: all
  sudo: True
  roles:
    - ansible-jenkins-swarm
     
  vars:     
    docker_files_generated_directory: ""  
    docker_files_enable: no    
    jenkins_home_dir: /var/lib/jenkins
    jenkins_username: tbd
    jenkins_password: tbd
