---
- hosts: all
  sudo: true
  roles:
    - { role: ./,
        docker_files_enable: yes,
        jenkins_home: /var/lib/jenkins,
        jenkins_username: tbd,
        jenkins_password: tbd  
      }

#- include: docker/integration-tests.yml
